logging:
   level:
      org:
         hibernate:
            type: trace
spring:
   datasource:
      driver-class-name: org.h2.Driver
      password: ''
      url: jdbc:h2:mem:testdb
      username: sa
   mail:
      host: smtp.gmail.com
      port: 587
      username: pruebaptv2@gmail.com
      password: ljag xdtj zlfs mzej
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.H2Dialect
            type: trace
      show-sql: false
   liquibase:
      change-log: classpath:db/changelog/databaseChangeLog.yml
      enabled: true
resilience4j:
   circuitbreaker:
      instances:
         accesoTecnicoService:
            registerHealthIndicator: true
            slidingWindowSize: 100
            minimumNumberOfCalls: 10
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 10s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10